/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VirtualGalleryRouteImport } from './routes/virtual-gallery'
import { Route as IndexRouteImport } from './routes/index'

const VirtualGalleryRoute = VirtualGalleryRouteImport.update({
  id: '/virtual-gallery',
  path: '/virtual-gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/virtual-gallery': typeof VirtualGalleryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/virtual-gallery': typeof VirtualGalleryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/virtual-gallery': typeof VirtualGalleryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/virtual-gallery'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/virtual-gallery'
  id: '__root__' | '/' | '/virtual-gallery'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VirtualGalleryRoute: typeof VirtualGalleryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/virtual-gallery': {
      id: '/virtual-gallery'
      path: '/virtual-gallery'
      fullPath: '/virtual-gallery'
      preLoaderRoute: typeof VirtualGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VirtualGalleryRoute: VirtualGalleryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
